// USER
export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED_START = 'USER_LOADED_START';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

// PROFILE
export const GET_PROFILE_START = 'GET_PROFILE_START';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const CREATE_PROFILE_START = 'CREATE_PROFILE_START';
export const CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS';
export const CREATE_PROFILE_ERRORS = 'CREATE_PROFILE_ERRORS';
export const CREATE_PROFILE_FAIL = 'CREATE_PROFILE_FAIL';

// BEERS
export const GET_PRODUCTS_START = 'GET_PRODUCTS_START';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';

// CART
export const TOGGLE_CART_HIDDEN = 'TOGGLE_CART_HIDDEN';
export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const DECREASE_ITEM_AMOUNT = 'DECREASE_ITEM_AMOUNT';
export const CLEAR_CART = 'CLEAR_CART';

// PAYMENT
export const PAYMENT_START = 'PAYMENT_START';
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS';
export const PAYMENT_FAIL = 'PAYMENT_FAIL';

// ORDERS
export const GET_ORDERS_START = 'GET_ORDERS_START';
export const GET_ORDERS = 'GET_ORDERS';
export const GET_ORDERS_ERROR = 'GET_ORDERS_ERROR';
export const CREATE_ORDER_START = 'ORDER_START';
export const CREATE_ORDER_SUCCESS = 'ORDER_SUCCESS';
export const CREATE_ORDER_FAIL = 'ORDER_FAIL';
export const CLEAR_ORDERS = 'CLEAR_ORDERS';
